### ISSUE TITLE
TOUCH_EVENT (click)

### ISSUE THREAD

**Issue by lucien144** [myflashlab/Statusbar-ANE#1]
Hey,
nice work! 👏 

Do you plan to add the touch event by any chance so we can finally implement that "tap status bar -> scroll up" thing? :)

Thanks.

**Comment by myflashlab** [comment]
I have marked this feature as an enhancement so we can investigate it more on the team as soon as possible.

**Comment by h3d-tuannq** [comment]
hi admin 
i want change statusbar background-color. How to make it?
thanks.

**Comment by myflashlab** [comment]
@quantuan this is an unrelated post to this topic, but as the documentation suggests:
```actionscript
Statusbar.changeStatusbarStyle(Statusbar.BAR_STYLE_DEFAULT, true);
Statusbar.changeStatusbarStyle(Statusbar.BAR_STYLE_LIGHT, true);
```

**Comment by sashthecash** [comment]
Hi, i'd also love to have this feature available, any updates yet?

**Comment by myflashlab** [comment]
**NOTICE:** This ANE is now opensourced. If you need our professional help, [check here](https://github.com/myflashlab/Statusbar-ANE/#tech-support)
