### ISSUE TITLE
Fails in iOS simulator

### ISSUE THREAD

**Issue by timoisalive** [myflashlab/Statusbar-ANE#3]
* iOS Version: 11.1 Simulator
* AIR SDK Version: 30

ArgumentError: Error #3500: The extension context does not have a method with the name command.

The ANE works on device, but fails with the above mentioned error in the simulator (Mac OS 10.12.6, XCode 9.1). You've mentioned elsewhere that your ANE's should be run on the device, not in simulator, but is this really the case, this ANE cannot be used in the simulator at all?

**Comment by myflashlab** [comment]
Yes, you can. Check this out: https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir#overrideairissupported

**Comment by timoisalive** [comment]
Thanks for the instant reply!
However, I'm still running into the same error, now when calling the OverrideAir.isSupported getter.
Also, initially I was hoping to control the statusbar in the simulator, but apparently this is not possible at all, is it?

**Comment by myflashlab** [comment]
Of course it's not possible. Simulator does not have a statusbar to be controlled. the iOS platform does.

**Comment by timoisalive** [comment]
Ok, didn't understand the simulator statusbar is not controllable.
The initial error is however still present, as mentioned before...

**Comment by myflashlab** [comment]
Well, as I mentioned before, you need to check with the overrideAIR ane first before initializing other ANEs:

```actionscript
if(!OverrideAir.isSupported)
{
	trace("These ANEs work on real devices only; not emulators");
	return;
}
```

make sure you are using the latest version of [overrideair V5.1.3](https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir#overrideairissupported)

**Comment by timoisalive** [comment]
Well, as I mentioned before, calling the OverrideAir.isSupported yields the error.

However, I dropped the Statusbar ANE completely, because losing the context (screen going black) when changing the statusbar mode was not good enough user experience. :(

**Comment by myflashlab** [comment]
The error ```ArgumentError: Error #3500: The extension context does not have a method with the name command``` can NOT happen when calling ```OverrideAir.isSupported``` because no native method is called from that property. UNLESS you are not using the latest version of the ANE.
